import { Client, Project } from '@/types';

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-001',
    name: 'Tariq Al-Mansoor',
    company: 'Apex Media Group',
    email: 'tariq@apexmedia.co',
    phone: '+971 50 123 4567',
    whatsapp: '+971501234567',
    status: 'active',
    notes: 'Very responsive client. Prefers updates via WhatsApp and weekly summary emails.',
    created_at: '2026-09-08T10:00:00.000Z',
  },
  {
    id: 'cli-002',
    name: 'Sarah Jenkins',
    company: 'CloudPulse SaaS',
    email: 'sarah@cloudpulse.io',
    phone: '+1 (415) 555-0192',
    whatsapp: '+14155550192',
    status: 'active',
    notes: 'Building their MVP. Next milestone is payment gateway and multi-tenant billing.',
    created_at: '2026-09-18T14:30:00.000Z',
  },
  {
    id: 'cli-003',
    name: 'Kareem Fahmy',
    company: 'Nile Artisan Roastery',
    email: 'kareem@nilecoffee.com',
    phone: '+20 100 234 5678',
    whatsapp: '+201002345678',
    status: 'completed',
    notes: 'E-commerce platform launched successfully. On quarterly maintenance retainer.',
    created_at: '2026-08-08T09:15:00.000Z',
  },
  {
    id: 'cli-004',
    name: 'Elena Rostova',
    company: 'Veloce Logistics',
    email: 'elena@velocelogistics.de',
    phone: '+49 170 987 6543',
    whatsapp: '+491709876543',
    status: 'pending',
    notes: 'Awaiting contract review and 50% upfront deposit before starting sprint 1.',
    created_at: '2026-10-03T11:00:00.000Z',
  },
  {
    id: 'cli-005',
    name: 'Zaid Al-Harbi',
    company: 'Bayan FinTech',
    email: 'zaid@bayan.sa',
    phone: '+966 55 876 5432',
    whatsapp: '+966558765432',
    status: 'inactive',
    notes: 'Project paused until Q4 budget approval.',
    created_at: '2026-07-10T08:00:00.000Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    client_id: 'cli-001',
    client_name: 'Apex Media Group',
    name: 'Apex Video Production Portal',
    description: 'Internal video asset management and client approval workflow portal.',
    live_url: 'https://portal.apexmedia.co',
    github_url: 'https://github.com/myaccount/apex-portal',
    vercel_url: 'https://apex-portal-prod.vercel.app',
    server_url: 'https://api.apexmedia.co',
    admin_url: 'https://portal.apexmedia.co/admin',
    image_url: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    tech_stack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Supabase', 'AWS S3'],
    status: 'live',
    deadline: '2026-10-25',
    notes: 'Deployed to Vercel production with custom domain and edge caching enabled.',
    total_price: 4800,
    amount_paid: 3200,
    remaining_amount: 1600,
    payment_status: 'partially_paid',
    currency: '$',
    created_at: '2026-09-12T10:00:00.000Z',
  },
  {
    id: 'proj-002',
    client_id: 'cli-002',
    client_name: 'CloudPulse SaaS',
    name: 'CloudPulse Monitoring Dashboard',
    description: 'Real-time infrastructure health monitoring web application with custom widgets.',
    live_url: 'https://app.cloudpulse.io',
    github_url: 'https://github.com/myaccount/cloudpulse-app',
    vercel_url: 'https://cloudpulse-staging.vercel.app',
    server_url: 'https://cloudpulse-backend.fly.dev',
    admin_url: 'https://app.cloudpulse.io/superadmin',
    image_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
    tech_stack: ['React', 'Next.js', 'TypeScript', 'PostgreSQL', 'Tailwind CSS'],
    status: 'in_development',
    deadline: '2026-10-14',
    notes: 'Developing sprint 3 analytics charts. Backend API hosted on Fly.io.',
    total_price: 6500,
    amount_paid: 2000,
    remaining_amount: 4500,
    payment_status: 'partially_paid',
    currency: '$',
    created_at: '2026-09-22T16:00:00.000Z',
  },
  {
    id: 'proj-003',
    client_id: 'cli-003',
    client_name: 'Nile Artisan Roastery',
    name: 'Nile Roastery E-Commerce',
    description: 'Specialty coffee storefront with subscription box builder and PayMob integration.',
    live_url: 'https://nilecoffee.com',
    github_url: 'https://github.com/myaccount/nile-coffee-shop',
    vercel_url: 'https://nile-coffee.vercel.app',
    server_url: 'https://api.nilecoffee.com',
    admin_url: 'https://nilecoffee.com/dashboard',
    image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    tech_stack: ['Next.js', 'Stripe', 'Tailwind CSS', 'Supabase', 'Framer Motion'],
    status: 'completed',
    notes: 'Handover complete. Documentation delivered to client.',
    total_price: 3500,
    amount_paid: 3500,
    remaining_amount: 0,
    payment_status: 'paid',
    currency: '$',
    created_at: '2026-08-12T12:00:00.000Z',
  },
  {
    id: 'proj-004',
    client_id: 'cli-004',
    client_name: 'Veloce Logistics',
    name: 'Dispatch Fleet Tracking Mobile Web App',
    description: 'Driver GPS dispatch console and route manifest tracking.',
    live_url: '',
    github_url: 'https://github.com/myaccount/veloce-fleet',
    vercel_url: '',
    server_url: '',
    admin_url: '',
    image_url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    tech_stack: ['Next.js', 'TypeScript', 'Tailwind CSS', 'Mapbox GL', 'Supabase'],
    status: 'in_development',
    notes: 'Initial prototype branch pushed. Waiting for deposit confirmation.',
    total_price: 5200,
    amount_paid: 0,
    remaining_amount: 5200,
    payment_status: 'unpaid',
    currency: '$',
    created_at: '2026-10-04T09:00:00.000Z',
  },
  {
    id: 'proj-005',
    client_id: 'cli-001',
    client_name: 'Apex Media Group',
    name: 'Brand Styleguide & Media Kit Website',
    description: 'Interactive brand guidelines and press downloadable assets hub.',
    live_url: 'https://brand.apexmedia.co',
    github_url: 'https://github.com/myaccount/apex-brand',
    vercel_url: 'https://apex-brand.vercel.app',
    server_url: '',
    admin_url: '',
    image_url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80',
    tech_stack: ['Next.js', 'MDX', 'Tailwind CSS'],
    status: 'maintenance',
    notes: 'Minor asset updates requested every month.',
    total_price: 1800,
    amount_paid: 1800,
    remaining_amount: 0,
    payment_status: 'paid',
    currency: '$',
    created_at: '2026-08-28T14:00:00.000Z',
  },
];
